owner: Banqzinc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Gateway dev
    url: https://dev.banqz.com/healthcheck
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: 'OK'
      
  - name: Gateway testing
    url: https://testing.banqz.com/healthcheck
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: 'OK'

  - name: Merchant backend dev
    url: https://merchant-portal-backend-dev-x5qcoeafba-ue.a.run.app/health_check
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: 'OK'

  - name: Merchant frontend dev
    url: https://merchant-portal-frontend-dev-x5qcoeafba-ue.a.run.app/healthcheck
    expectedStatusCodes:
      - 200
      
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.banqz.com
  # baseUrl: /your-repo-name
  logoUrl: https://banqz.com/img/logo_white_desktop.png
  name: Banqz Status
  introTitle: Banqz Status
  introMessage: Banqz Status
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://banqz.com
assignees: # Users to assign downtime issues (optional)
  - Ohad-Lu
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 22 * * *"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
